### ISSUE TITLE
English Version?

### ISSUE THREAD

**Issue by 69remrem** [sanmusen214/arisstudio-blockly#1]
Will there be an english version for this?

**Comment by sanmusen214** [comment]
The i18n framework was decided to be done in the version of 0.3 which would fit ArisStudio 0.3, but ArisStudio stopped maintaining at the version 0.2.25, while 0.3 was keeping at the laboratory version. I highly recommend everyone to try another useful tool to create BA story : [AzureArchive](https://aadoc.foxxlight.top/) , which is updated actively and has a user-friendly interface. 

There is another way that is creating a new branch of ArisStudio-Blockly_0.2.25 and simply change all displaying texts to English (which is fast and easy) and then build it. This could be discussed again after you take a try to [AzureArchive](https://aadoc.foxxlight.top/).

**Comment by sanmusen214** [comment]
This one could be closed since no more reply. If you have more questions, feel free to open a new one.
